language: android
addons:
  apt:
    packages:
      - python-openssl
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - pip install --user `whoami` google-api-python-client

script: releases/travis_build.sh

after_script:
  - releases/publish_s3.sh
  - releases/publish_playstore.py

android:
  components:
    - build-tools-22.0.1
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

sudo: false
before_install:
  - openssl aes-256-cbc -K $encrypted_6a3fa2e8cfe5_key -iv $encrypted_6a3fa2e8cfe5_iv
    -in releases/google-play-key.p12.enc -out releases/google-play-key.p12 -d
