language: android
addons:
  apt:
    packages:
      - python3-openssl

before_script:
  - 'export PATH="$HOME/.local/bin:$PATH"'
  - pip install --user google-api-python-client oauth2client httplib2
# broken, see below with git depth 99999
#  - git fetch --unshallow

script: releases/travis_build.sh

after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && releases/publish_s3.sh'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && releases/publish_playstore_v3.py'

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

sudo: true
before_install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_6a3fa2e8cfe5_key -iv $encrypted_6a3fa2e8cfe5_iv
    -in releases/google-play-key.p12.enc -out releases/google-play-key.p12 -d || true'
  - sed -i "s/versionCode.*/versionCode $(git rev-list HEAD --first-parent --count)/" app/build.gradle
  # https://stackoverflow.com/a/47726910/1449683
  - yes | sdkmanager "platforms;android-27"

# Workaround for https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999

notifications:
  irc:
    channels:
      # travis encrypt "ircs://irc.freenode.net:6697/#weechat-android" -r ubergeek42/weechat-android
      - secure: "iytIkREUR4PsjBevyWZ0nx3eLbelSjyIT4E6jFyMH9YdTAMEBrS9W7zEG4WzhBsAYaKJvhwRw2N3L9ZB6bLDclmW2r9OvctISjpecogDr2kN5U9FgXG4IO/2js16/voitPH+zN6skHcksqLJ/VkmGGwzO2SKg15Rh9J+T9SBZio="
    template:
      - "#%{build_number} (%{commit} @ %{branch} by %{author}): %{message}"
      - "Message: %{commit_subject}"
      - "Changes: %{compare_url}"

# Edit this line when you want to trigger a travis build. Count: 4
