language: android
addons:
  apt:
    packages:
      - python-openssl

before_script:
  - 'export PATH="$HOME/.local/bin:$PATH"'
  - pip install --user google-api-python-client
# broken, see below with git depth 99999
#  - git fetch --unshallow

script: releases/travis_build.sh

after_script:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && releases/publish_s3.sh'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && releases/publish_playstore.py'

android:
  components:
    - build-tools-25.0.2
    - android-23
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository

sudo: true
before_install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_6a3fa2e8cfe5_key -iv $encrypted_6a3fa2e8cfe5_iv
    -in releases/google-play-key.p12.enc -out releases/google-play-key.p12 -d || true'
  - sed -i "s/versionCode.*/versionCode $(git rev-list HEAD --first-parent --count)/" weechat-android/build.gradle

# Workaround for https://github.com/travis-ci/travis-ci/issues/4942
git:
  depth: 99999

# Edit this line when you want to trigger a travis build. Count: 1
